using System.Text;
using Kpm.Artifacts;
using Kpm.Model;
using Kpm.Packing;
using Kpm.Resolution;

namespace Kpm.Install;

public sealed record InstalledPackage(PackageId Id, PackageVersion Version, string Directory, string IncludePath);

/// <summary>
/// Puts resolved packages into a project.
///
/// Packages land under <c>Lib/KPM/&lt;owner&gt;/&lt;name&gt;/</c>, and beside each one the installer
/// writes a small forwarder script so a consumer writes <c>#Include &lt;KPM/owner/name&gt;</c> and
/// never has to know the archive's internal layout. The forwarder is generated, so a package can
/// move its entry file between versions without every consumer editing an include line.
/// </summary>
public sealed class Installer(ArtifactStore store)
{
	public const string LibraryRoot = "Lib";
	public const string Namespace = "KPM";

	public static string PackageDirectory(string projectDirectory, PackageId id) =>
		Path.Combine(projectDirectory, LibraryRoot, Namespace, id.Owner, id.Name);

	public static string ForwarderPath(string projectDirectory, PackageId id) =>
		Path.Combine(projectDirectory, LibraryRoot, Namespace, id.Owner, $"{id.Name}.ks");

	public async Task<IReadOnlyList<InstalledPackage>> InstallAsync(DependencyResolution resolution, string projectDirectory,
																   CancellationToken ct = default)
	{
		var installed = new List<InstalledPackage>();

		foreach (var package in resolution.Packages)
		{
			var bytes = await store.GetAsync(package.Artifact, $"{package.Id} {package.Release}", ct);
			installed.Add(Unpack(bytes, projectDirectory, package.Id, package.Release, package.Manifest.Entry));
		}

		Prune(projectDirectory, resolution.Packages.Select(p => p.Id).ToHashSet());
		return installed;
	}

	public async Task<IReadOnlyList<InstalledPackage>> InstallAsync(LockFile lockFile, string projectDirectory,
																   CancellationToken ct = default)
	{
		var installed = new List<InstalledPackage>();

		foreach (var locked in lockFile.Packages)
		{
			var id = PackageId.Parse(locked.Id);
			var version = new PackageVersion(Semver.SemVersion.Parse(locked.Version), locked.Revision);
			var bytes = await store.GetAsync(locked.Sha256, locked.Sources, $"{id} {version}", ct);
			installed.Add(Unpack(bytes, projectDirectory, id, version, locked.Entry));
		}

		Prune(projectDirectory, lockFile.Packages.Select(p => PackageId.Parse(p.Id)).ToHashSet());
		return installed;
	}

	private static InstalledPackage Unpack(byte[] archive, string projectDirectory, PackageId id,
										   PackageVersion version, string entry)
	{
		var directory = PackageDirectory(projectDirectory, id);
		Unpacker.Extract(archive, directory);

		if (string.IsNullOrEmpty(entry))
			entry = Unpacker.ReadManifest(archive).Entry;

		WriteForwarder(projectDirectory, id, version, entry);
		return new InstalledPackage(id, version, directory, $"{Namespace}/{id.Owner}/{id.Name}");
	}

	/// <summary>
	/// Writes <c>Lib/KPM/&lt;owner&gt;/&lt;name&gt;.ks</c>, which the lib-include syntax resolves and
	/// which does nothing but include the package's entry file. Paths are forward-slashed: that is
	/// the separator lib includes accept on every platform.
	/// </summary>
	private static void WriteForwarder(string projectDirectory, PackageId id, PackageVersion version, string entry)
	{
		var path = ForwarderPath(projectDirectory, id);
		_ = Directory.CreateDirectory(Path.GetDirectoryName(path)!);
		var text = new StringBuilder()
		.Append("; Generated by kpm. Do not edit: reinstalling this package overwrites it.\n")
		.Append($"; {id} {version.ToDisplayString()}\n")
		.Append($"#Include %A_LineFile%/../{id.Name}/{entry}\n")
		.ToString();
		File.WriteAllText(path, text, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
	}

	/// <summary>
	/// Removes packages the project no longer depends on. Only ever touches the generated
	/// <c>Lib/KPM</c> tree, so a hand-maintained <c>Lib</c> beside it is left alone.
	/// </summary>
	private static void Prune(string projectDirectory, IReadOnlySet<PackageId> keep)
	{
		var root = Path.Combine(projectDirectory, LibraryRoot, Namespace);

		if (!Directory.Exists(root))
			return;

		foreach (var ownerDirectory in Directory.EnumerateDirectories(root))
		{
			var owner = Path.GetFileName(ownerDirectory);

			foreach (var packageDirectory in Directory.EnumerateDirectories(ownerDirectory))
			{
				var name = Path.GetFileName(packageDirectory);

				if (PackageId.TryParse($"{owner}/{name}", out var id, out _) && keep.Contains(id.Value))
					continue;

				Directory.Delete(packageDirectory, recursive: true);
				var forwarder = Path.Combine(ownerDirectory, $"{name}.ks");

				if (File.Exists(forwarder))
					File.Delete(forwarder);
			}

			if (!Directory.EnumerateFileSystemEntries(ownerDirectory).Any())
				Directory.Delete(ownerDirectory);
		}
	}
}
